version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgresuser
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
  hasura:
    image: hasura/graphql-engine:v1.3.3
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgresuser:postgrespassword@postgres:5432/postgresdb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, websocket-log, query-log
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  auth:
    image: nhost/hasura-backend-plus:v2.5.0
    restart: always
    environment:
      DATABASE_URL: postgres://postgresuser:postgrespassword@postgres:5432/postgresdb
      SERVER_URL: http://localhost:3000/v1
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: hasurasecret
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - hasura

